version: "3.8"

services:
  app:
    build: .
    container_name: ogrenciden-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/ogrencidenDB

  db:
    image: postgres:15
    container_name: ogrenciden-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ogrencidenDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
